### ISSUE TITLE
MongoDB Seed Script does not work

### ISSUE THREAD

**Issue by TaylorBeeston** [Fabianopb/create-fullstack-react-app#9]
The seed script for Mongo is currently mixing CommonJS and ES6 imports (CommonJS in the script file, ES6 imports in the Model files). The simplest solution I have found for this is to simply update the script file to use ES6 imports, then run the script with [babel-node](https://babeljs.io/docs/en/next/babel-node.html).

**Comment by Fabianopb** [comment]
Patch `1.3.2` released!
